"""test_available_range.py — verify ExternalReference.available_range
wiring for clips generated by clipwright-noise (_add_full_clip).

Context (project-conventions.md / ADR-4, src/clipwright/otio_utils.py add_clip):
  clipwright.otio_utils.add_clip wires MediaRef.available_range into
  ExternalReference.available_range when the caller supplies it. noise.py's
  _add_full_clip builds the ExternalReference manually (does not call
  add_clip) and sets available_range directly, since the full-clip case
  (_add_full_clip is only used for whole-file clips) always knows the exact
  media duration.

Verification points:
  (a) New timeline (timeline=None): V1 clip's ExternalReference.available_range
      must be set (not None).
  (b) available_range must equal the full source duration (same start_time /
      duration as the clip's source_range, since _add_full_clip always
      creates a full-length keep clip).
  (c) source_range must be contained within available_range (subset
      invariant: start_time >= available_range.start_time and
      end_time_exclusive <= available_range.end_time_exclusive).
  (d) Existing-timeline-with-empty-V1 branch (_load_and_validate_timeline →
      _add_full_clip) must also wire available_range.

Mock strategy mirrors test_noise.py: patch inspect_media / measure_noise,
then load the actually-saved .otio file back and inspect the OTIO clip
objects directly (no float-seconds comparisons; RationalTime/TimeRange only,
per coding-standards.md OTIO test rules).
"""

from __future__ import annotations

from pathlib import Path
from unittest.mock import patch

import opentimelineio as otio
from clipwright.otio_utils import load_timeline
from clipwright.schemas import MediaInfo, RationalTimeModel, StreamInfo

from clipwright_noise.noise import detect_noise
from clipwright_noise.schemas import DetectNoiseOptions

FPS = 30.0
_FAKE_MEASURE_RESULT = {
    "params": {"nr": 12.0, "nf": -50.0, "nt": "w"},
    "measured_noise_floor_db": -50.0,
    "warnings": [],
}


def _make_media_info(
    path: str,
    *,
    duration_sec: float = 10.0,
    rate: float = FPS,
) -> MediaInfo:
    """Build a MediaInfo with both video and audio streams for testing."""
    streams = [
        StreamInfo(index=0, codec_type="video", codec_name="h264"),
        StreamInfo(index=1, codec_type="audio", codec_name="aac"),
    ]
    return MediaInfo(
        path=path,
        container="mov,mp4,m4a,3gp,3g2,mj2",
        duration=RationalTimeModel(value=duration_sec * rate, rate=rate),
        streams=streams,
        bit_rate=8_000_000,
    )


def _video_clips(tl: otio.schema.Timeline) -> list[otio.schema.Clip]:
    v1 = next(t for t in tl.tracks if t.kind == otio.schema.TrackKind.Video)
    return [item for item in v1 if isinstance(item, otio.schema.Clip)]


def _audio_clips(tl: otio.schema.Timeline) -> list[otio.schema.Clip]:
    a1 = next(t for t in tl.tracks if t.kind == otio.schema.TrackKind.Audio)
    return [item for item in a1 if isinstance(item, otio.schema.Clip)]


class TestAvailableRangeNewTimeline:
    """(a)(b)(c): timeline=None → new timeline via _add_full_clip."""

    def test_v1_clip_available_range_is_set(self, tmp_path: Path) -> None:
        """ExternalReference.available_range must not be None (a)."""
        media = tmp_path / "video.mp4"
        media.write_bytes(b"dummy")
        output = tmp_path / "out.otio"
        media_info = _make_media_info(str(media))

        with (
            patch("clipwright_noise.noise.inspect_media", return_value=media_info),
            patch(
                "clipwright_noise.noise.measure_noise",
                return_value=_FAKE_MEASURE_RESULT,
            ),
        ):
            detect_noise(str(media), str(output), DetectNoiseOptions(), timeline=None)

        tl = load_timeline(str(output))
        clips = _video_clips(tl)
        assert len(clips) == 1
        ref = clips[0].media_reference
        assert isinstance(ref, otio.schema.ExternalReference)
        assert ref.available_range is not None, (
            "ExternalReference.available_range must be wired for the "
            "full-length clip generated by _add_full_clip."
        )

    def test_available_range_matches_full_source_duration(self, tmp_path: Path) -> None:
        """available_range must span the full media duration, matching
        source_range exactly for a full-length keep clip (b)."""
        media = tmp_path / "video.mp4"
        media.write_bytes(b"dummy")
        output = tmp_path / "out.otio"
        media_info = _make_media_info(str(media), duration_sec=10.0, rate=FPS)

        with (
            patch("clipwright_noise.noise.inspect_media", return_value=media_info),
            patch(
                "clipwright_noise.noise.measure_noise",
                return_value=_FAKE_MEASURE_RESULT,
            ),
        ):
            detect_noise(str(media), str(output), DetectNoiseOptions(), timeline=None)

        tl = load_timeline(str(output))
        clip = _video_clips(tl)[0]
        ref = clip.media_reference
        assert isinstance(ref, otio.schema.ExternalReference)
        assert ref.available_range is not None
        assert ref.available_range.start_time == clip.source_range.start_time
        assert ref.available_range.duration == clip.source_range.duration

    def test_source_range_is_subset_of_available_range(self, tmp_path: Path) -> None:
        """source_range must fit within available_range (c)."""
        media = tmp_path / "video.mp4"
        media.write_bytes(b"dummy")
        output = tmp_path / "out.otio"
        media_info = _make_media_info(str(media), duration_sec=10.0, rate=FPS)

        with (
            patch("clipwright_noise.noise.inspect_media", return_value=media_info),
            patch(
                "clipwright_noise.noise.measure_noise",
                return_value=_FAKE_MEASURE_RESULT,
            ),
        ):
            detect_noise(str(media), str(output), DetectNoiseOptions(), timeline=None)

        tl = load_timeline(str(output))
        clip = _video_clips(tl)[0]
        ref = clip.media_reference
        assert isinstance(ref, otio.schema.ExternalReference)
        assert ref.available_range is not None

        src = clip.source_range
        avail = ref.available_range
        assert src.start_time >= avail.start_time
        assert src.end_time_exclusive() <= avail.end_time_exclusive()

    def test_a1_clip_available_range_is_also_set(self, tmp_path: Path) -> None:
        """The A1 clip (its own ExternalReference instance, built from the
        same values as V1's) must also carry available_range, since
        _add_full_clip appends an equivalent clip to both the Video and
        Audio tracks."""
        media = tmp_path / "video.mp4"
        media.write_bytes(b"dummy")
        output = tmp_path / "out.otio"
        media_info = _make_media_info(str(media))

        with (
            patch("clipwright_noise.noise.inspect_media", return_value=media_info),
            patch(
                "clipwright_noise.noise.measure_noise",
                return_value=_FAKE_MEASURE_RESULT,
            ),
        ):
            detect_noise(str(media), str(output), DetectNoiseOptions(), timeline=None)

        tl = load_timeline(str(output))
        clips = _audio_clips(tl)
        assert len(clips) == 1
        ref = clips[0].media_reference
        assert isinstance(ref, otio.schema.ExternalReference)
        assert ref.available_range is not None


class TestAvailableRangeEmptyV1Branch:
    """(d): existing timeline with empty V1 → _load_and_validate_timeline
    falls back to _add_full_clip; available_range must be wired there too."""

    def test_empty_v1_full_clip_available_range_is_set(self, tmp_path: Path) -> None:
        media = tmp_path / "video.mp4"
        media.write_bytes(b"dummy")
        output = tmp_path / "out.otio"
        media_info = _make_media_info(str(media), duration_sec=8.0, rate=FPS)

        # Build an existing timeline with empty V1/A1 tracks.
        existing_tl = otio.schema.Timeline(name="existing")
        existing_tl.tracks.append(
            otio.schema.Track(name="V1", kind=otio.schema.TrackKind.Video)
        )
        existing_tl.tracks.append(
            otio.schema.Track(name="A1", kind=otio.schema.TrackKind.Audio)
        )
        existing_timeline_path = tmp_path / "existing.otio"
        otio.adapters.write_to_file(existing_tl, str(existing_timeline_path))

        with (
            patch("clipwright_noise.noise.inspect_media", return_value=media_info),
            patch(
                "clipwright_noise.noise.measure_noise",
                return_value=_FAKE_MEASURE_RESULT,
            ),
        ):
            detect_noise(
                str(media),
                str(output),
                DetectNoiseOptions(),
                timeline=str(existing_timeline_path),
            )

        tl = load_timeline(str(output))
        clips = _video_clips(tl)
        assert len(clips) == 1
        ref = clips[0].media_reference
        assert isinstance(ref, otio.schema.ExternalReference)
        assert ref.available_range is not None
