"""Shared fixtures for clipwright-transcribe tests.

Loads tests/fixtures/whisper_sample.json (generated by spike-whisper) and provides
it as the foundation for normalize_segments tests.
See fixtures/README.md for whether a fixture is "confirmed" or "hypothetical".
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

FIXTURES_DIR = Path(__file__).parent / "fixtures"


@pytest.fixture(scope="session")
def whisper_sample_json() -> dict[str, Any]:
    """Return the whisper_sample.json generated by spike-whisper as a dict.

    Status: hypothetical (real binary not confirmed; CLIPWRIGHT_WHISPER env not set).
    See fixtures/README.md for the confirmed/hypothetical distinction.
    """
    path = FIXTURES_DIR / "whisper_sample.json"
    with path.open(encoding="utf-8") as f:
        data: dict[str, Any] = json.load(f)
    return data
