"""test_word_captions.py — Red-phase tests for word-level captions logic (s1-captions-test).

Tests for the not-yet-implemented word-level functions in captions.py:
  extract_word_segments, to_word_vtt, words_for_otio, WordSegment, WordTiming,
  MAX_WORDS_TRANSCRIBE

All tests in this module FAIL on collection (ImportError / Red phase) because
captions.py does not yet export these symbols.  This is the intended Red state:
the import error indicates missing implementation, not a broken test.

Existing Segment / normalize_segments / to_srt / to_vtt tests in test_captions.py
are unaffected — this file is purely additive.

Observation coverage:
  AC-1 / F-T-02 / F-T-03 / F-T-04 / SEC-03 / CWE-400
  ADR-K8: MAX_WORDS_TRANSCRIBE = 50_000
  spike: spike-whisper-word.md (tokens schema / word-reconstruction rules confirmed)
  fixture: whisper_word_sample.json (3 segments: special-token / BPE / degenerate)
  contract: word_vtt_canonical.vtt (s0-contract-fixture source-of-truth)
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest
from clipwright.errors import ClipwrightError, ErrorCode

# New symbols below raise ImportError until s1-captions-impl is merged (correct Red).
from clipwright_transcribe.captions import (
    MAX_WORDS_TRANSCRIBE,
    WordSegment,
    extract_word_segments,
    to_word_vtt,
    words_for_otio,
)

# ---------------------------------------------------------------------------
# Fixtures & helpers
# ---------------------------------------------------------------------------

FIXTURES_DIR = Path(__file__).parent / "fixtures"


@pytest.fixture(scope="session")
def whisper_word_sample_json() -> dict[str, Any]:
    """Return whisper_word_sample.json (generated by s0-spike-whisper) as a dict.

    Contains 3 segments covering: [_BEG_] special-token, BPE sub-word merge,
    and degenerate interval (offsets.from >= offsets.to) cases.
    """
    path = FIXTURES_DIR / "whisper_word_sample.json"
    with path.open(encoding="utf-8") as f:
        data: dict[str, Any] = json.load(f)
    return data


@pytest.fixture(scope="session")
def word_vtt_canonical_text() -> str:
    """Return word_vtt_canonical.vtt content (s0-contract-fixture source-of-truth)."""
    path = FIXTURES_DIR / "word_vtt_canonical.vtt"
    return path.read_text(encoding="utf-8")


def _make_large_whisper_json(n_words: int) -> dict[str, Any]:
    """Build a synthetic whisper JSON with n_words valid word tokens.

    Each token starts with a leading space (= new word boundary) and has
    non-degenerate offsets.  Used for CWE-400 boundary tests.
    """
    tokens: list[dict[str, Any]] = []
    for i in range(n_words):
        tokens.append(
            {
                "text": f" w{i}",
                "offsets": {"from": i * 100, "to": (i + 1) * 100},
                "id": 100 + (i % 1000),
                "p": 0.9,
                "t_dtw": -1,
            }
        )
    return {
        "transcription": [
            {
                "offsets": {"from": 0, "to": n_words * 100},
                "text": "many words",
                "tokens": tokens,
            }
        ]
    }


# Word-segments that reproduce word_vtt_canonical.vtt byte-for-byte.
# Built from the grammar fixed in s0-contract-fixture (architecture ADR-K1).
CANONICAL_WORD_SEGMENTS: list[WordSegment] = [
    {
        "start_sec": 1.0,
        "end_sec": 3.5,
        "text": "Hello world this is a test",
        "words": [
            {"text": "Hello", "start_sec": 1.0, "end_sec": 1.4},
            {"text": "world", "start_sec": 1.4, "end_sec": 1.9},
            {"text": "this", "start_sec": 1.9, "end_sec": 2.3},
            {"text": "is", "start_sec": 2.3, "end_sec": 2.6},
            {"text": "a", "start_sec": 2.6, "end_sec": 2.9},
            {"text": "test", "start_sec": 2.9, "end_sec": 3.5},
        ],
    },
    {
        "start_sec": 4.0,
        "end_sec": 6.2,
        "text": "With karaoke support enabled",
        "words": [
            {"text": "With", "start_sec": 4.0, "end_sec": 4.5},
            {"text": "karaoke", "start_sec": 4.5, "end_sec": 5.1},
            {"text": "support", "start_sec": 5.1, "end_sec": 5.7},
            {"text": "enabled", "start_sec": 5.7, "end_sec": 6.2},
        ],
    },
]


# ===========================================================================
# extract_word_segments — BPE merging / special-token / degenerate filtering
# ===========================================================================


class TestExtractWordSegments:
    """Verify extract_word_segments reconstructs words from whisper_word_sample.json.

    The fixture has 3 segments that each exercise one reconstruction rule:
      seg1 (" Okay.")          — [_BEG_] special-token filtering
      seg2 (" I'm going …")    — BPE sub-word merge (' I' + "'m" → "I'm")
      seg3 (" Oh, I'm going…") — degenerate interval (offsets from == to) exclusion
    """

    def test_returns_list(self, whisper_word_sample_json: dict[str, Any]) -> None:
        """extract_word_segments returns a list (AC-1 / F-T-02)."""
        result = extract_word_segments(whisper_word_sample_json)
        assert isinstance(result, list)

    def test_segment_count_three(
        self, whisper_word_sample_json: dict[str, Any]
    ) -> None:
        """All 3 fixture segments (each has start_sec < end_sec) are preserved."""
        result = extract_word_segments(whisper_word_sample_json)
        assert len(result) == 3

    # -----------------------------------------------------------------------
    # Segment 1: " Okay." (0–1000 ms)
    # [_BEG_] special-token excluded; BPE "." merged onto " Okay"
    # -----------------------------------------------------------------------

    def test_segment1_word_count(
        self, whisper_word_sample_json: dict[str, Any]
    ) -> None:
        """Segment 1 yields 1 word ('Okay.' — BPE '.' joined to ' Okay')."""
        result = extract_word_segments(whisper_word_sample_json)
        assert len(result[0]["words"]) == 1

    def test_segment1_word_text(self, whisper_word_sample_json: dict[str, Any]) -> None:
        """Segment 1 word text is 'Okay.' (leading space stripped; BPE '.' merged)."""
        result = extract_word_segments(whisper_word_sample_json)
        assert result[0]["words"][0]["text"] == "Okay."

    def test_segment1_word_start_sec(
        self, whisper_word_sample_json: dict[str, Any]
    ) -> None:
        """'Okay.' word.start_sec = offsets.from of ' Okay' token / 1000 = 0.0 s."""
        result = extract_word_segments(whisper_word_sample_json)
        assert result[0]["words"][0]["start_sec"] == pytest.approx(0.0)

    def test_segment1_word_end_sec(
        self, whisper_word_sample_json: dict[str, Any]
    ) -> None:
        """'Okay.' word.end_sec = offsets.to of '.' token / 1000 = 0.990 s."""
        result = extract_word_segments(whisper_word_sample_json)
        assert result[0]["words"][0]["end_sec"] == pytest.approx(0.990)

    def test_special_token_beg_excluded(
        self, whisper_word_sample_json: dict[str, Any]
    ) -> None:
        """[_BEG_] token (text.startswith('[_')) must not appear in any word text."""
        result = extract_word_segments(whisper_word_sample_json)
        all_texts = [w["text"] for seg in result for w in seg["words"]]
        assert not any("[_BEG_]" in t for t in all_texts)

    def test_special_token_tt_excluded(
        self, whisper_word_sample_json: dict[str, Any]
    ) -> None:
        """[_TT_N] timestamp tokens (text.startswith('[_')) must not appear in any word."""
        result = extract_word_segments(whisper_word_sample_json)
        all_texts = [w["text"] for seg in result for w in seg["words"]]
        assert not any(t.startswith("[_") for t in all_texts)

    # -----------------------------------------------------------------------
    # Segment 2: " I'm going to go." (1000–2000 ms)
    # BPE sub-word: ' I' (new word) + "'m" (no leading space → same word) → "I'm"
    # -----------------------------------------------------------------------

    def test_bpe_subword_merged_into_one_word(
        self, whisper_word_sample_json: dict[str, Any]
    ) -> None:
        """' I' + \"'m\" (no leading space) must merge into 'I'm', not stay separate."""
        result = extract_word_segments(whisper_word_sample_json)
        seg2_texts = [w["text"] for w in result[1]["words"]]
        assert "'m" not in seg2_texts, 'BPE sub-word "\'m" must be merged, not separate'
        assert "I'm" in seg2_texts

    def test_segment2_word_count(
        self, whisper_word_sample_json: dict[str, Any]
    ) -> None:
        """Segment 2 has 4 words: 'I'm' / 'going' / 'to' / 'go.'."""
        result = extract_word_segments(whisper_word_sample_json)
        assert len(result[1]["words"]) == 4

    def test_segment2_words_text_in_order(
        self, whisper_word_sample_json: dict[str, Any]
    ) -> None:
        """Segment 2 word texts are [\"I'm\", 'going', 'to', 'go.'] in order."""
        result = extract_word_segments(whisper_word_sample_json)
        seg2_texts = [w["text"] for w in result[1]["words"]]
        assert seg2_texts == ["I'm", "going", "to", "go."]

    def test_segment2_first_word_start_sec(
        self, whisper_word_sample_json: dict[str, Any]
    ) -> None:
        """'I'm' word.start_sec = offsets.from of ' I' token / 1000 = 1.0 s."""
        result = extract_word_segments(whisper_word_sample_json)
        assert result[1]["words"][0]["start_sec"] == pytest.approx(1.0)

    def test_segment2_first_word_end_sec(
        self, whisper_word_sample_json: dict[str, Any]
    ) -> None:
        """'I'm' word.end_sec = offsets.to of \"'m\" token / 1000 = 1.190 s."""
        result = extract_word_segments(whisper_word_sample_json)
        assert result[1]["words"][0]["end_sec"] == pytest.approx(1.190)

    # -----------------------------------------------------------------------
    # Segment 3: " Oh, I'm going to come." (3000–4000 ms)
    # Degenerate interval: tokens at 4000-4000 ms must be excluded
    # -----------------------------------------------------------------------

    def test_degenerate_tokens_excluded_segment3(
        self, whisper_word_sample_json: dict[str, Any]
    ) -> None:
        """Tokens with offsets.from >= offsets.to (4000-4000 ms) must not become words.

        'going', 'to', 'come' are all at 4000-4000 ms (degenerate) in the fixture
        and must be excluded from the word list.
        """
        result = extract_word_segments(whisper_word_sample_json)
        seg3_texts = [w["text"] for w in result[2]["words"]]
        assert "going" not in seg3_texts
        assert "to" not in seg3_texts
        assert "come" not in seg3_texts

    def test_segment3_word_count(
        self, whisper_word_sample_json: dict[str, Any]
    ) -> None:
        """Segment 3 has 2 words after degenerate filtering: 'Oh,' and 'I'."""
        result = extract_word_segments(whisper_word_sample_json)
        assert len(result[2]["words"]) == 2

    def test_segment3_words_text_in_order(
        self, whisper_word_sample_json: dict[str, Any]
    ) -> None:
        """Segment 3 word texts are ['Oh,', 'I'] (degenerate tail excluded)."""
        result = extract_word_segments(whisper_word_sample_json)
        seg3_texts = [w["text"] for w in result[2]["words"]]
        assert seg3_texts == ["Oh,", "I"]

    # -----------------------------------------------------------------------
    # WordSegment structure — start_sec / end_sec / text from segment-level offsets
    # -----------------------------------------------------------------------

    def test_segment_start_sec_from_offsets(
        self, whisper_word_sample_json: dict[str, Any]
    ) -> None:
        """WordSegment.start_sec = segment offsets.from / 1000."""
        result = extract_word_segments(whisper_word_sample_json)
        assert result[0]["start_sec"] == pytest.approx(0.0)  # seg1: 0 ms
        assert result[1]["start_sec"] == pytest.approx(1.0)  # seg2: 1000 ms
        assert result[2]["start_sec"] == pytest.approx(3.0)  # seg3: 3000 ms

    def test_segment_end_sec_from_offsets(
        self, whisper_word_sample_json: dict[str, Any]
    ) -> None:
        """WordSegment.end_sec = segment offsets.to / 1000."""
        result = extract_word_segments(whisper_word_sample_json)
        assert result[0]["end_sec"] == pytest.approx(1.0)  # seg1: 1000 ms
        assert result[1]["end_sec"] == pytest.approx(2.0)  # seg2: 2000 ms
        assert result[2]["end_sec"] == pytest.approx(4.0)  # seg3: 4000 ms

    def test_segment_text_stripped(
        self, whisper_word_sample_json: dict[str, Any]
    ) -> None:
        """WordSegment.text is stripped (mirrors normalize_segments behaviour)."""
        result = extract_word_segments(whisper_word_sample_json)
        assert result[0]["text"] == "Okay."
        assert result[1]["text"] == "I'm going to go."
        assert result[2]["text"] == "Oh, I'm going to come."

    def test_empty_transcription_returns_empty_list(self) -> None:
        """extract_word_segments with empty transcription list returns []."""
        result = extract_word_segments({"transcription": []})
        assert result == []


# ===========================================================================
# to_word_vtt — inline timestamp format / cue structure / monotonic ordering
# ===========================================================================


class TestToWordVtt:
    """Verify to_word_vtt output format (AC-1 / F-T-03)."""

    def test_starts_with_webvtt_header(self) -> None:
        """Output starts with 'WEBVTT' header (WebVTT spec)."""
        vtt = to_word_vtt(CANONICAL_WORD_SEGMENTS)
        assert vtt.startswith("WEBVTT")

    def test_one_cue_per_segment(self) -> None:
        """Each WordSegment produces exactly one VTT cue (one '-->' per segment)."""
        vtt = to_word_vtt(CANONICAL_WORD_SEGMENTS)
        assert vtt.count("-->") == len(CANONICAL_WORD_SEGMENTS)

    def test_cue_timecode_is_segment_range(self) -> None:
        """Cue start/end timecode matches WordSegment.start_sec / end_sec (AC-1)."""
        vtt = to_word_vtt(CANONICAL_WORD_SEGMENTS)
        # seg1: 1.0 s → 3.5 s
        assert "00:00:01.000 --> 00:00:03.500" in vtt
        # seg2: 4.0 s → 6.2 s
        assert "00:00:04.000 --> 00:00:06.200" in vtt

    def test_inline_timestamp_pattern(self) -> None:
        """Inline timestamps match the <HH:MM:SS.mmm> pattern (architecture §2-1)."""
        import re

        vtt = to_word_vtt(CANONICAL_WORD_SEGMENTS)
        inline_ts_re = re.compile(r"<\d{2}:\d{2}:\d{2}\.\d{3}>")
        assert inline_ts_re.search(vtt), (
            f"No inline timestamp <HH:MM:SS.mmm> found in VTT output: {vtt!r}"
        )

    def test_inline_timestamps_monotonically_increasing(self) -> None:
        """All inline timestamps in the document are monotonically non-decreasing (AC-1)."""
        import re

        vtt = to_word_vtt(CANONICAL_WORD_SEGMENTS)
        ts_re = re.compile(r"<(\d{2}:\d{2}:\d{2}\.\d{3})>")
        timestamps = ts_re.findall(vtt)
        assert len(timestamps) > 0, "No inline timestamps found"
        for prev, curr in zip(timestamps, timestamps[1:], strict=False):
            assert prev <= curr, (
                f"Inline timestamps not monotonically increasing: {prev!r} > {curr!r}"
            )

    def test_ms_separator_is_dot(self) -> None:
        """Timecodes use '.' millisecond separator (not ',') — _format_timecode
        ms_separator='.' consistency (DC-AS-005 / architecture §2-1)."""
        import re

        vtt = to_word_vtt(CANONICAL_WORD_SEGMENTS)
        # Cue header must have dot-separated timecode
        assert re.search(r"\d{2}:\d{2}:\d{2}\.\d{3} -->", vtt)
        # Must NOT contain SRT-style comma separator
        assert not re.search(r"\d{2}:\d{2}:\d{2},\d{3}", vtt)

    def test_empty_word_segments_returns_header_only(self) -> None:
        """to_word_vtt([]) returns output containing only the WEBVTT header (DC-GP-002 parity)."""
        vtt = to_word_vtt([])
        assert "WEBVTT" in vtt
        assert "-->" not in vtt


# ===========================================================================
# Roundtrip — to_word_vtt output must match word_vtt_canonical.vtt byte-for-byte
# ===========================================================================


class TestToWordVttRoundtrip:
    """Roundtrip: known word_segments → to_word_vtt → byte-identical with canonical fixture.

    word_vtt_canonical.vtt (s0-contract-fixture) is the source of truth for the
    word-level VTT grammar.  This test pins the serialisation contract so that
    both transcribe (producer) and render (consumer) are bound to the same bytes.

    CANONICAL_WORD_SEGMENTS is the authoritative input that must produce the
    canonical VTT.  The fixture is read directly rather than hard-coded to avoid
    duplication with s0-contract-fixture.
    """

    def test_roundtrip_canonical_vtt_byte_match(
        self, word_vtt_canonical_text: str
    ) -> None:
        """to_word_vtt(CANONICAL_WORD_SEGMENTS) == word_vtt_canonical.vtt (byte-exact)."""
        result = to_word_vtt(CANONICAL_WORD_SEGMENTS)
        assert result == word_vtt_canonical_text, (
            "VTT output does not match canonical fixture.\n"
            f"Expected:\n{word_vtt_canonical_text!r}\n"
            f"Got:\n{result!r}"
        )


# ===========================================================================
# words_for_otio — flatten to [{text, start, end}]
# ===========================================================================


class TestWordsForOtio:
    """Verify words_for_otio flattens WordSegment.words to OTIO metadata format (F-T-04).

    OTIO schema: [{text: str, start: float, end: float}]
    Note: keys are 'start'/'end' (not 'start_sec'/'end_sec') to match OTIO convention.
    """

    def test_returns_list(self) -> None:
        """words_for_otio returns a list."""
        result = words_for_otio(CANONICAL_WORD_SEGMENTS)
        assert isinstance(result, list)

    def test_flatten_all_words(self) -> None:
        """Words from all segments are flattened into one list (6 + 4 = 10 words)."""
        result = words_for_otio(CANONICAL_WORD_SEGMENTS)
        assert len(result) == 10

    def test_each_entry_has_text_start_end_keys(self) -> None:
        """Each entry has exactly the keys text / start / end (OTIO schema contract)."""
        result = words_for_otio(CANONICAL_WORD_SEGMENTS)
        for entry in result:
            assert "text" in entry
            assert "start" in entry
            assert "end" in entry

    def test_word_text_values_correct(self) -> None:
        """First word is 'Hello'; last word is 'enabled' (spot-check)."""
        result = words_for_otio(CANONICAL_WORD_SEGMENTS)
        assert result[0]["text"] == "Hello"
        assert result[-1]["text"] == "enabled"

    def test_start_end_values_correct(self) -> None:
        """start / end match the word's start_sec / end_sec in float seconds."""
        result = words_for_otio(CANONICAL_WORD_SEGMENTS)
        # First word: "Hello", start=1.0 s, end=1.4 s
        assert result[0]["start"] == pytest.approx(1.0)
        assert result[0]["end"] == pytest.approx(1.4)
        # Second word: "world", start=1.4 s
        assert result[1]["start"] == pytest.approx(1.4)

    def test_empty_segments_returns_empty_list(self) -> None:
        """words_for_otio([]) returns [] (no words to flatten)."""
        result = words_for_otio([])
        assert result == []


# ===========================================================================
# CWE-400 — MAX_WORDS_TRANSCRIBE = 50_000 guard (SEC-03 / ADR-K8)
# ===========================================================================


class TestCWE400MaxWords:
    """Verify extract_word_segments raises INVALID_INPUT when word count > 50_000.

    ADR-K8: MAX_WORDS_TRANSCRIBE = 50_000
    Headroom: 30-min short ≈ 5,400 words (3 word/s) → ~10x safety margin.
    50_000 words ≈ 2 MB ASS when rendered — safe upper bound.
    """

    def test_max_words_constant_value(self) -> None:
        """MAX_WORDS_TRANSCRIBE must equal 50_000 (drift guard, ADR-K8)."""
        assert MAX_WORDS_TRANSCRIBE == 50_000

    def test_exceeds_max_words_raises_invalid_input(self) -> None:
        """50_001 valid words → ClipwrightError with code INVALID_INPUT (CWE-400)."""
        large_json = _make_large_whisper_json(50_001)
        with pytest.raises(ClipwrightError) as exc_info:
            extract_word_segments(large_json)
        assert exc_info.value.code == ErrorCode.INVALID_INPUT

    def test_hint_contains_limit_value(self) -> None:
        """The error hint must mention the 50_000 upper limit (AC-6 / ADR-K8).

        The hint should also include guidance to split the input.
        """
        large_json = _make_large_whisper_json(50_001)
        with pytest.raises(ClipwrightError) as exc_info:
            extract_word_segments(large_json)
        hint = exc_info.value.hint
        assert "50000" in hint or "50_000" in hint, (
            f"Hint does not mention the 50_000 word limit: {hint!r}"
        )

    def test_exactly_max_words_does_not_raise(self) -> None:
        """Exactly 50_000 words is within the limit and must not raise (boundary value)."""
        exact_json = _make_large_whisper_json(50_000)
        result = extract_word_segments(exact_json)
        assert len(result) == 1
        assert len(result[0]["words"]) == 50_000
