"""schemas.py — clipwright-noise-specific Pydantic schemas.

Common types (MediaRef / Artifact / ToolResult, etc.) are defined centrally
in clipwright.schemas and are not redefined here.

DetectNoiseOptions: Input options for clipwright_detect_noise.
DenoiseDirective: Directive schema written to timeline-level
    metadata["clipwright"]["denoise"].
AfftdnParams: afftdn filter parameters (body of DenoiseDirective.params).
"""

from __future__ import annotations

import math
from typing import Annotated, Any, Literal

from pydantic import BaseModel, Field, field_validator


class DetectNoiseOptions(BaseModel):
    """Options for clipwright_detect_noise (design §2.1).

    The `track` field is deprecated (ADR-N7).
    The first audio stream is processed unconditionally.
    """

    backend: Annotated[
        Literal["afftdn", "deepfilternet"],
        Field(
            default="afftdn",
            description=(
                "Denoise backend. "
                '"afftdn" (default) applies the ffmpeg afftdn filter at render time. '
                '"deepfilternet" generates annotations only; '
                "render application is not supported (first release)."
            ),
        ),
    ] = "afftdn"

    strength: Annotated[
        Literal["light", "medium", "strong"],
        Field(
            default="medium",
            description=(
                "Strength mapped to afftdn nr (noise reduction dB). "
                "light=6 / medium=12 / strong=24 (fixed values). "
                "Not referenced when using the deepfilternet backend."
            ),
        ),
    ] = "medium"


class AfftdnParams(BaseModel):
    """afftdn filter parameters (design §2.2 / DC-AS-006).

    Used when render re-validates DenoiseDirective.params as AfftdnParams.
    Applied only when backend=="afftdn".
    """

    nr: Annotated[
        float,
        Field(ge=0.01, le=97, description="Noise reduction (dB). Range [0.01, 97]."),
    ]
    nf: Annotated[
        float,
        Field(ge=-80, le=-20, description="Noise floor (dB). Range [-80, -20]."),
    ]
    nt: Annotated[
        Literal["w", "v"],
        Field(default="w", description="Noise type. w=white noise (default), v=vinyl."),
    ] = "w"


class DenoiseDirective(BaseModel):
    """Denoise directive schema written to timeline-level metadata (design §2.2).

    Generated by noise; loaded and validated by render.
    When backend=="afftdn", params is a dict equivalent to AfftdnParams
    (re-validated by render).
    When backend=="deepfilternet", params is fixed to {} (first release).
    """

    tool: Annotated[str, Field(max_length=64)]
    version: Annotated[str, Field(max_length=64)]
    kind: Literal["denoise"]
    backend: Literal["afftdn", "deepfilternet"]
    params: dict[str, Any]
    measured_noise_floor_db: Annotated[float, Field(ge=-200.0, le=0.0)] | None = None

    @field_validator("measured_noise_floor_db", mode="before")
    @classmethod
    def _reject_non_finite(cls, v: object) -> object:
        """Reject inf / nan (CWE-20: invalid numeric value elimination)."""
        if isinstance(v, float) and not math.isfinite(v):
            raise ValueError("inf / nan cannot be used for measured_noise_floor_db.")
        return v
