"""schemas.py — Pydantic models for clipwright-reframe.

Common types (MediaRef / Artifact / ToolResult) are imported from core (clipwright)
and are never redefined here.
"""

from __future__ import annotations

import re
from typing import Annotated, Literal

from pydantic import BaseModel, Field, field_validator

# CSS named colors accepted as pad_color.  This is a curated subset of the
# ffmpeg color names that are safe to embed in a filtergraph string (no
# special characters, no injection risk).  Extend as needed; keep sorted.
_NAMED_COLORS: frozenset[str] = frozenset(
    {
        "black",
        "blue",
        "cyan",
        "gray",
        "green",
        "grey",
        "magenta",
        "red",
        "white",
        "yellow",
    }
)

# Hex color: #RRGGBB or 0xRRGGBB (case-insensitive, exactly 6 hex digits)
_HEX_COLOR_RE = re.compile(r"^(#|0x)[0-9A-Fa-f]{6}$")


def _validate_even(value: int, field_name: str) -> int:
    """Raise ValueError if *value* is odd (must be even for ffmpeg codec alignment)."""
    if value % 2 != 0:
        raise ValueError(f"{field_name} must be an even number, got {value}")
    return value


def _validate_pad_color(value: str) -> str:
    """Accept only CSS color names from the allowlist or #RRGGBB / 0xRRGGBB hex.

    Rejects any string containing filtergraph special characters (comma,
    semicolon, brackets, etc.) or that does not match the allowlist.
    This prevents command-injection via the pad= filter argument (AC-05).
    """
    stripped = value.strip()
    if stripped != value or not stripped:
        raise ValueError(
            f"pad_color must not be empty or contain leading/trailing"
            f" whitespace: {value!r}"
        )
    if value in _NAMED_COLORS:
        return value
    if _HEX_COLOR_RE.match(value):
        return value
    raise ValueError(
        f"pad_color {value!r} is not in the allowed list. "
        "Use a CSS color name (black, white, red, …) or #RRGGBB / 0xRRGGBB hex."
    )


class ReframeOptions(BaseModel):
    """Options for clipwright_reframe.

    target_w: Target output width in pixels (must be even, 2-7680).
    target_h: Target output height in pixels (must be even, 2-7680).
    mode: Fit mode — 'crop' (cover, then crop), 'pad' (fit, then letterbox/pillarbox),
          or 'blur_pad' (fit foreground over blurred background).
    anchor: Crop/pad alignment anchor (9-direction).
    pad_color: Background color for pad mode (CSS color name or hex).
    """

    model_config = {"extra": "forbid", "allow_inf_nan": False}

    target_w: Annotated[
        int,
        Field(
            ge=1,
            le=7680,
            description="Target output width in pixels (must be even, 2-7680).",
        ),
    ]
    target_h: Annotated[
        int,
        Field(
            ge=1,
            le=7680,
            description="Target output height in pixels (must be even, 2-7680).",
        ),
    ]
    mode: Annotated[
        Literal["crop", "pad", "blur_pad"],
        Field(
            default="pad",
            description=(
                "Fit mode: 'crop' (cover+crop), 'pad' (fit+letterbox/pillarbox),"
                " 'blur_pad' (fit foreground over blurred background). Default 'pad'."
            ),
        ),
    ] = "pad"
    anchor: Annotated[
        Literal[
            "center",
            "top",
            "bottom",
            "left",
            "right",
            "top_left",
            "top_right",
            "bottom_left",
            "bottom_right",
        ],
        Field(
            default="center",
            description=(
                "Crop/pad alignment anchor (9-direction). Ignored for blur_pad mode."
                " Default 'center'."
            ),
        ),
    ] = "center"
    pad_color: Annotated[
        str,
        Field(
            default="black",
            max_length=64,
            description=(
                "Background fill color for pad mode (CSS color name or #RRGGBB hex)."
                " Ignored for blur_pad. Default 'black'."
            ),
        ),
    ] = "black"

    @field_validator("target_w")
    @classmethod
    def target_w_must_be_even(cls, v: int) -> int:
        """Reject odd target_w — ffmpeg requires even dimensions for most codecs."""
        return _validate_even(v, "target_w")

    @field_validator("target_h")
    @classmethod
    def target_h_must_be_even(cls, v: int) -> int:
        """Reject odd target_h — ffmpeg requires even dimensions for most codecs."""
        return _validate_even(v, "target_h")

    @field_validator("pad_color")
    @classmethod
    def pad_color_must_be_safe(cls, v: str) -> str:
        """Accept only allowlisted color names or #RRGGBB / 0xRRGGBB hex (AC-05)."""
        return _validate_pad_color(v)


class ReframeDirective(BaseModel):
    """Directive written to timeline metadata["clipwright"]["reframe"].

    Generated by clipwright-reframe and read/validated by clipwright-render.
    Carries the target resolution, fit mode, anchor, and pad color.

    The key set (tool / version / kind / target_w / target_h / mode / anchor /
    pad_color) is frozen as the D3 both-sides contract.  Any change must be
    coordinated with render's _RenderReframe reader.
    """

    model_config = {"extra": "forbid", "allow_inf_nan": False}

    tool: Annotated[str, Field(max_length=64)] = "clipwright-reframe"
    version: Annotated[str, Field(max_length=64)]
    kind: Literal["reframe"]
    target_w: Annotated[int, Field(ge=1, le=7680)]
    target_h: Annotated[int, Field(ge=1, le=7680)]
    mode: Literal["crop", "pad", "blur_pad"] = "pad"
    anchor: Literal[
        "center",
        "top",
        "bottom",
        "left",
        "right",
        "top_left",
        "top_right",
        "bottom_left",
        "bottom_right",
    ] = "center"
    pad_color: Annotated[str, Field(max_length=64)] = "black"

    @field_validator("target_w")
    @classmethod
    def target_w_must_be_even(cls, v: int) -> int:
        """Defence-in-depth: reject odd target_w on the reader side as well."""
        return _validate_even(v, "target_w")

    @field_validator("target_h")
    @classmethod
    def target_h_must_be_even(cls, v: int) -> int:
        """Defence-in-depth: reject odd target_h on the reader side as well."""
        return _validate_even(v, "target_h")

    @field_validator("pad_color")
    @classmethod
    def pad_color_must_be_safe(cls, v: str) -> str:
        """Defence-in-depth: reject unsafe pad_color on the reader side (AC-05)."""
        return _validate_pad_color(v)
