"""schemas.py — Pydantic models for clipwright-reframe.

Common types (MediaRef / Artifact / ToolResult) are imported from core (clipwright)
and are never redefined here.

W1 will flesh out ReframeOptions and ReframeDirective with full field definitions.
This scaffold provides the minimal structure to allow import resolution.
"""

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, Field


class ReframeOptions(BaseModel):
    """Options for clipwright_reframe.

    target_w: Target output width in pixels (must be even, 2-7680).
    target_h: Target output height in pixels (must be even, 2-7680).
    mode: Fit mode — 'crop' (cover, then crop), 'pad' (fit, then letterbox/pillarbox),
          or 'blur_pad' (fit foreground over blurred background).
    anchor: Crop/pad alignment anchor (9-direction).
    pad_color: Background color for pad mode (CSS color name or hex).
    """

    model_config = {"extra": "forbid", "allow_inf_nan": False}

    target_w: Annotated[
        int,
        Field(
            ge=2,
            le=7680,
            description="Target output width in pixels (must be even).",
        ),
    ]
    target_h: Annotated[
        int,
        Field(
            ge=2,
            le=7680,
            description="Target output height in pixels (must be even).",
        ),
    ]
    mode: Annotated[
        Literal["crop", "pad", "blur_pad"],
        Field(
            default="pad",
            description=(
                "Fit mode: 'crop' (cover+crop), 'pad' (fit+letterbox/pillarbox),"
                " 'blur_pad' (fit foreground over blurred background). Default 'pad'."
            ),
        ),
    ] = "pad"
    anchor: Annotated[
        Literal[
            "center",
            "top",
            "bottom",
            "left",
            "right",
            "top_left",
            "top_right",
            "bottom_left",
            "bottom_right",
        ],
        Field(
            default="center",
            description=(
                "Crop/pad alignment anchor (9-direction). Ignored for blur_pad mode."
                " Default 'center'."
            ),
        ),
    ] = "center"
    pad_color: Annotated[
        str,
        Field(
            default="black",
            max_length=64,
            description=(
                "Background fill color for pad mode (CSS color name or #RRGGBB hex)."
                " Ignored for blur_pad. Default 'black'."
            ),
        ),
    ] = "black"


class ReframeDirective(BaseModel):
    """Directive written to timeline metadata["clipwright"]["reframe"].

    Generated by clipwright-reframe and read/validated by clipwright-render.
    Carries the target resolution, fit mode, anchor, and pad color.
    """

    model_config = {"extra": "forbid", "allow_inf_nan": False}

    tool: Annotated[str, Field(max_length=64)] = "clipwright-reframe"
    version: Annotated[str, Field(max_length=64)]
    kind: Literal["reframe"]
    target_w: Annotated[int, Field(ge=2, le=7680)]
    target_h: Annotated[int, Field(ge=2, le=7680)]
    mode: Literal["crop", "pad", "blur_pad"] = "pad"
    anchor: Literal[
        "center",
        "top",
        "bottom",
        "left",
        "right",
        "top_left",
        "top_right",
        "bottom_left",
        "bottom_right",
    ] = "center"
    pad_color: Annotated[str, Field(max_length=64)] = "black"
