"""schemas.py — Pydantic models for clipwright-color.

Common types (MediaRef / Artifact / ToolResult) are imported from core (clipwright)
and are never redefined here.
"""

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, Field


class DetectColorOptions(BaseModel):
    """Options for clipwright_detect_color.

    target_luma: target average luma (0-255 scale). Default 128 (mid-grey).
    sample_interval_sec: ffmpeg fps=1/interval downsampling step (seconds, >0).
    """

    model_config = {"extra": "forbid"}

    target_luma: Annotated[
        float,
        Field(
            default=128.0,
            ge=0.0,
            le=255.0,
            allow_inf_nan=False,
            description="Target average luma on the 0-255 scale. Default 128.",
        ),
    ] = 128.0

    sample_interval_sec: Annotated[
        float,
        Field(
            default=1.0,
            gt=0.0,
            le=3600.0,
            allow_inf_nan=False,
            description=(
                "Frame sampling interval in seconds (ffmpeg fps=1/interval)."
                " Must be > 0. Default 1.0."
            ),
        ),
    ] = 1.0


class BrightnessMeasured(BaseModel):
    """Raw signalstats measurement (writer side).

    yavg is the mean of per-frame lavfi.signalstats.YAVG values.
    ymin/ymax are optional aggregates (min of YMIN, max of YMAX) for diagnostics.
    sampled_frames is the number of frames that produced a YAVG value.
    inf/nan are rejected; the caller degrades to measured=None (parity with
    loudness U-1).
    """

    model_config = {"extra": "forbid", "allow_inf_nan": False}

    yavg: Annotated[float, Field(ge=0.0, le=255.0)]
    ymin: Annotated[float, Field(ge=0.0, le=255.0)] | None = None
    ymax: Annotated[float, Field(ge=0.0, le=255.0)] | None = None
    sampled_frames: Annotated[int, Field(ge=0)]


class EqParams(BaseModel):
    """eq filter parameters consumed by clipwright-render (writer side).

    Defaults are neutral so the full eq string can always be applied
    unconditionally on the render side. Ranges match ffmpeg eq filter limits.
    """

    model_config = {"extra": "forbid", "allow_inf_nan": False}

    brightness: Annotated[float, Field(ge=-1.0, le=1.0)] = 0.0
    contrast: Annotated[float, Field(ge=0.0, le=2.0)] = 1.0
    saturation: Annotated[float, Field(ge=0.0, le=2.0)] = 1.0
    gamma: Annotated[float, Field(ge=0.1, le=10.0)] = 1.0


class ColorDirective(BaseModel):
    """Directive written to timeline metadata["clipwright"]["color"].

    Generated by clipwright-color and read/validated by clipwright-render.
    scope is timeline-level only (per_clip deferred). measured is optional
    (None when measurement failed; parity with loudness U-1).
    """

    model_config = {"extra": "forbid"}

    tool: Annotated[str, Field(max_length=64)] = "clipwright-color"
    version: Annotated[str, Field(max_length=64)]
    kind: Literal["color"]
    target_luma: Annotated[float, Field(ge=0.0, le=255.0, allow_inf_nan=False)]
    measured: BrightnessMeasured | None = None
    eq: EqParams
