"""conftest.py — Shared fixtures for clipwright-wrap tests.

Loads tests/fixtures/budoux_sample.json generated by spike-budoux and provides
real budoux phrase-boundary segments as inputs for greedy line-filling tests.
Fixtures are confirmed (all 4 languages loaded successfully; parse() -> list[str] API verified).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

FIXTURES_DIR = Path(__file__).parent / "fixtures"


@pytest.fixture(scope="session")
def budoux_sample_json() -> dict[str, Any]:
    """Load budoux_sample.json (generated by spike-budoux) and return it as a dict.

    Status: confirmed (all 4 languages loaded successfully via spike-budoux; real budoux output).
    See fixtures/README.md for confirmed details.
    """
    path = FIXTURES_DIR / "budoux_sample.json"
    with path.open(encoding="utf-8") as f:
        data: dict[str, Any] = json.load(f)
    return data


@pytest.fixture(scope="session")
def budoux_segments_ja(budoux_sample_json: dict[str, Any]) -> list[list[str]]:
    """Return the Japanese segment list (4 samples) from budoux_sample.json.

    Each element is a list of phrase-boundary tokens (list[str]) for one cue.
    - [0]: ["今日は", "いい", "天気です。"]
    - [1]: ["今日は", "とても", "いい", "天気なので", "公園に", "散歩に", "行きました。"]
    - [2]: long text (9 segments)
    - [3]: mixed alphanumeric (6 segments)
    """
    segments: list[list[str]] = [list(s) for s in budoux_sample_json["segments"]]
    return segments
