"""schemas.py — Pydantic models for clipwright-stabilize.

Common types (MediaRef / Artifact / ToolResult) are imported from core
(clipwright) and are never redefined here.
"""

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, Field


class DetectShakeOptions(BaseModel):
    """Options for clipwright_detect_shake.

    shakiness: vidstabdetect shakiness (1-10). Higher = assume more shake.
    accuracy:  vidstabdetect accuracy (1-15). Higher = more accurate / slower.
    smoothing: vidstabtransform smoothing window (frames, 0-1000). Consumed by
        clipwright-render at apply time; recorded here for round-trip.
    """

    model_config = {"extra": "forbid", "allow_inf_nan": False}

    shakiness: Annotated[int, Field(ge=1, le=10)] = 5
    accuracy: Annotated[int, Field(ge=1, le=15)] = 15
    smoothing: Annotated[int, Field(ge=0, le=1000)] = 12


class StabilizeDirective(BaseModel):
    """Directive written to timeline metadata["clipwright"]["stabilize"].

    Generated by clipwright-stabilize and read/validated by clipwright-render.
    scope is timeline-level / single-source only (per-source deferred).

    severity is best-effort (None when the binary .trf could not be parsed).
    recommendation is an advisory hint derived from severity via
    _SEVERITY_APPLY_THRESHOLD; the calling agent makes the final decision.
    recommendation defaults to None when the field was not computed (backward
    compat with directives written before this field was introduced).
    """

    model_config = {"extra": "forbid", "allow_inf_nan": False}

    tool: Annotated[str, Field(max_length=64)] = "clipwright-stabilize"
    version: Annotated[str, Field(max_length=64)]
    kind: Literal["stabilize"]
    trf_path: str  # absolute path (record only; render splits to dir/basename)
    # ge/le constraints reject out-of-range values when render model_validates from
    # external OTIO (SR-NEW).  _estimate_severity always clamps to [0.0, 1.0] itself.
    severity: Annotated[float, Field(ge=0.0, le=1.0)] | None = None
    recommendation: Literal["skip", "apply"] | None = (
        None  # advisory; None = not computed
    )
    shakiness: Annotated[int, Field(ge=1, le=10)]
    accuracy: Annotated[int, Field(ge=1, le=15)]
    smoothing: Annotated[int, Field(ge=0, le=1000)]
